### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Arnold1** [mlverse/libtorch-mac-m1#1]
hi,

do you also have libtorch 1.13.0 and libtorch 1.11.0 for download?

just download, extract the lib and store under /usr/lib?

Thanks

**Comment by dfalbel** [comment]
Hi @Arnold1 ,

I just made v1.13.1 and v1.13.0 available. Unfortunatelly, I don't think the current workflow works for v1.11.0, and I'm not sure it actually supports MPS devices.

**Comment by Arnold1** [comment]
@dfalbel thank you - isn't m1/m2 officially supported by PyTorch? im ok not having v1.11.0.

**Comment by dfalbel** [comment]
I think it's still a Beta feature in PyTorch and unfortunatelly they don't provide pre-built binaries for C++.

**Comment by Arnold1** [comment]
what about PyTorch for python using apple m1?

**Comment by dfalbel** [comment]
AFAICT you can install for Python on M1 using the official channels. With conda or pip.

**Comment by Arnold1** [comment]
@dfalbel do you have somewhere a PyTorch classification model example I can look at and test out? im ok with r code or python as well...
