### ISSUE TITLE
Pre-build libtorch 2.0

### ISSUE THREAD

**Issue by polvalente** [mlverse/libtorch-mac-m1#2]
Hi! I was wondering if it would be possible for a new pre-built version for Libtorch 2.0.0 on M1

**Comment by dfalbel** [comment]
Hi! Just made it available in: https://github.com/mlverse/libtorch-mac-m1/releases/tag/LibTorch

Thanks for reaching out!

**Comment by polvalente** [comment]
Thank you so much!
