### ISSUE TITLE
Provide more details about building libtorch for m1

### ISSUE THREAD

**Issue by xiejw** [mlverse/libtorch-mac-m1#3]
Hi there, thanks for providing the builds!!!

I am trying to follow the same steps to reproduce the builds on M1. But keep hitting different errors. 

1. First realized we need XCode  (not just Command Line) which has Metal framework.
2. After that, getting a different error
```
[100%] Linking CXX executable ../../../../bin/torch_shm_manager
Undefined symbols for architecture arm64:
  "_MTLCopyAllDevices", referenced from:
      at::mps::MPSDevice::MPSDevice() in libtorch_cpu.a(MPSDevice.mm.o)
  "_NSClassFromString", referenced from:
      at::mps::MPSDevice::MPSDevice() in libtorch_cpu.a(MPSDevice.mm.o)
  "_OBJC_CLASS_$_MPSCommandBuffer", referenced from:
      objc-class-ref in libtorch_cpu.a(MPSStream.mm.o)
  "_OBJC_CLASS_$_MPSGraph", referenced from:
      objc-class-ref in libtorch_cpu.a(OperationUtils.mm.o)
  "_OBJC_CLASS_$_MPSGraphConvolution2DOpDescriptor", referenced from:
      objc-class-ref in libtorch_cpu.a(Convolution.mm.o)
```

Can you help to give some details in README file about how to prepare the compilation env? Thanks

My cmake cmd is
```
cmake -D USE_OPENMP=OFF -D USE_MPS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=../install ../pytorch
```

**Comment by dfalbel** [comment]
Hi,

Unfortunatelly I manually configured that machine and forgot to take notes on everuthing that I had to install.
I added some information to the README file, like eg OS version, conda packages information, etc.
I'm not sure what your issue really is. Have you tried opening Xcode to accept the license and downloading authorizing it to download the macOS SDK's? 

Let me know if you need any additional information from the system.

**Comment by xiejw** [comment]
I have attached my config at the end. I think I **found the issue** by trial and error. The `-DBUILD_SHARED_LIBS=OFF` should not be used on mac as static lib is likely a bad idea. Thanks for your speedy reply and help!

The new cmake works
```
 cmake \
      -G Ninja \
      -D USE_MPS=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE:STRING=Release \
      -DPYTHON_EXECUTABLE:PATH=`which python3` \
      -DCMAKE_INSTALL_PREFIX:PATH=../install \
      ../pytorch
```

My config

```
config >
  macos 13.2.1
  cmake 3.26.0
  xcode 14.3 (also cross-checked here https://developer.apple.com/support/xcode/)
  macos sdk 13.3 (xcrun --show-sdk-version)
  clang (apple --version)
    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    Target: arm64-apple-darwin22.3.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
