### ISSUE TITLE
Build libtorch(openmp) 2.1.0

### ISSUE THREAD

**Issue by zap150** [mlverse/libtorch-mac-m1#6]
Could you please provide packages for the new release? Btw. why are the packages on pythorch.org built without MPS?

**Comment by dfalbel** [comment]
Hi,
I have just added v2.10 to the releases page.
I don't why they don't provide ARM builds for LibTorch :( would be really nice actually.

**Comment by zap150** [comment]
Is the tag `LibTorchLibTorch` correct? :-) [LibTorchLibTorch](https://github.com/mlverse/libtorch-mac-m1/releases/tag/LibTorchLibTorch)
